---
- name: Install Node.js and PM2 on EC2
  hosts: ec2
  become: true  # Corrected from 'truie'

  tasks:
    - name: Update package lists (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Add Nginx reverse proxy configuration
      copy:
        dest: /etc/nginx/sites-available/myapp.conf
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Enable Nginx site configuration
      file:
        src: /etc/nginx/sites-available/myapp.conf
        dest: /etc/nginx/sites-enabled/myapp.conf
        state: link

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      changed_when: nginx_test.rc != 0

    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted




