---
- name: Setting password
  hosts: localhost
  become : yes

  tasks:
  - name: Set Password
    user:
      name: divyasree
      update_password: always
      password: "{{'abcd1234' | password_hash('sha512')}}"
